# Generated by Django 4.0 on 2022-01-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-created_at']},
        ),
    ]
